# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb-to-rails3}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Kulik", "Piotr Solnica"]
  s.date = %q{2010-03-31}
  s.email = %q{tech@llp.pl}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "TODO.markdown",
     "VERSION.yml",
     "lib/merb-to-rails3.rb",
     "lib/merb-to-rails3/controller_exceptions.rb",
     "lib/merb-to-rails3/helpers.rb",
     "merb-to-rails3.gemspec"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/LunarLogicPolska/merb-to-rails3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Small library that will help you to port a Merb-based app to Rails3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

